# Generated by Django 4.0.6 on 2022-07-31 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('creation', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=10)),
                ('tier', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('limit', models.FloatField()),
                ('number', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=50)),
                ('is_extension', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.account')),
            ],
        ),
    ]
