# Generated by Django 4.0.6 on 2022-07-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_corporate',
            field=models.BooleanField(default=False),
        ),
    ]
