# Generated by Django 4.0.6 on 2022-07-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_account_is_corporate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='tier',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
