# Generated by Django 4.0.6 on 2022-07-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0005_alter_operation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='category',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
