# Generated by Django 4.0.6 on 2022-07-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0006_operation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
