# Generated by Django 4.0.6 on 2022-07-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0007_card_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
