# Generated by Django 4.0.6 on 2022-08-01 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0008_alter_operation_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('entity', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.account')),
            ],
        ),
        migrations.CreateModel(
            name='OperationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('entity', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.card')),
            ],
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
