# Generated by Django 4.0.6 on 2022-08-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0010_bill_operationbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='has_inconsistency',
            field=models.BooleanField(default=False),
        ),
    ]
