# Generated by Django 4.1 on 2022-08-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0012_operationcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
