# Generated by Django 4.1 on 2022-08-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0013_accountcategories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountCategories',
        ),
    ]
