# Generated by Django 4.1 on 2022-08-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0014_delete_accountcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationcard',
            name='dues',
            field=models.IntegerField(default=1),
        ),
    ]
