# Generated by Django 4.1 on 2022-08-27 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0016_operationaccount_dues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationaccount',
            name='dues',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
