# Generated by Django 4.1 on 2022-08-29 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0018_operationaccount_trip_operationcard_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'trips_trip',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='operationaccount',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashflow.trip'),
        ),
        migrations.AlterField(
            model_name='operationcard',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashflow.trip'),
        ),
    ]
