# Generated by Django 4.1 on 2022-08-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0020_alter_operationcard_dues_alter_operationcard_trip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'managed': True},
        ),
    ]
