# Generated by Django 4.1 on 2022-08-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0022_trip_accomodation_trip_car_trip_is_incomplete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='is_incomplete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
