# Generated by Django 4.1 on 2022-08-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0023_alter_trip_is_incomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='car',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
