# Generated by Django 4.1 on 2022-08-31 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0025_alter_trip_car_alter_trip_shopping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationcard',
            name='trip',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cashflow.trip'),
        ),
    ]
