# Generated by Django 4.1 on 2022-09-01 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0027_alter_operationcard_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationaccount',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.operationcategories'),
        ),
        migrations.AlterField(
            model_name='operationcard',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.operationcategories'),
        ),
    ]
