# Generated by Django 4.1 on 2022-09-05 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0028_alter_operationaccount_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationaccount',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.trip'),
        ),
        migrations.AlterField(
            model_name='operationcard',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.trip'),
        ),
    ]
