# Generated by Django 4.1 on 2022-09-13 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0029_alter_operationaccount_trip_alter_operationcard_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationbill',
            name='op_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.operationcard'),
        ),
    ]
