# Generated by Django 4.1 on 2023-03-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0031_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationcard',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
