# Generated by Django 4.1 on 2022-08-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trip',
            table='trips_trip',
        ),
    ]
